### ISSUE TITLE
Error running in Win7 x64

### ISSUE THREAD

**Issue by praveenax** [MidEndProject/node-pdf2img#5]
Encountered this error while trying to run in my system. Is there a solution for this issue?

`events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn pdfinfo ENOENT
    at exports._errnoException (util.js:870:11)

`

**Comment by mass44** [comment]
Hello, same issue for me, any clue how to solve this ?

**Comment by AndreySurzhan** [comment]
Hi all.
I would advice install this tool http://www.foolabs.com/xpdf/

In my case I had the similar problem with pdfinfo on my Mac.
Reinstalling pdfinfo package, using different package managers and so on didn't help.
I figure out that pdfinfo is used only for getting page count of given pdf file.
So I decided to use gm native methods to get number of pages instead of pdfinfo
here https://github.com/MidEndProject/node-pdf2img/blob/master/lib/pdf2img.js#L42

```
                    // Get page count from PDF file
                        function (pdfPath, callback) {
                            var cmd = 'identify -format %n ' + pdfPath;
                            var execSync = require('child_process').execSync; //note that this method is in node ~v0.12.0
                            var pageCount;

                            pageCount = execSync(cmd);

                            callback(null, pageCount)
                        }

```

 `identify -format %n` 
where: 
`-format`  - When used with the identify utility, or the convert utility with output written to the 'info:-' file specification, use this option to print information about the image in a format of your choosing. You can include the image filename, type, width, height, Exif data, or other image attributes by embedding special format characters
`%n` - number of scenes

**Comment by fitraditya** [comment]
Nice!

I plan to remove pdfinfo for the next release, and will try to use `identify` command. Hope it will fix pdfinfo issue in windows.
